dist: trusty
sudo: false
group: beta

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
addons:
  apt:
    packages:
      - php5
      - php5-curl
      - php5-cli
      - php5-intl

before_install:
  - gem update --system
  - gem install sass
  - php --version
  - php -r "readfile('https://getcomposer.org/installer');" | php && php composer.phar config -g github-oauth.github.com $GH_AUTH
  - npm update -g npm
  - npm install -g bower grunt-cli jspm yarn gulp
  - jspm config registries.github.auth $JSPM_AUTH
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sf' ]; then cd .. && eval "mv $currentfolder generator-sf" && cd generator-sf; fi
  - yarn

before_script:
  - phpenv config-rm xdebug.ini

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
    - test/fixtures/bower_components
    - test/fixtures/jspm_packages
