'use strict';
module.exports =  {<% if (props.loader === 'webpack') { %>
    all: ['<%%= paths.app %>/scripts/**/*.js']<% } else { %>
    all: [
        '<%%= paths.app %>/scripts/**/*.js',
        // don't lint as this is autogenerated
        '!<%%= paths.app %>/scripts/config.js'
    ]<% } %>
};
